"""`armar-manager` Protocol for talking to a single `armar-agentd`.

This is the *single* seam the UI view-models depend on. The
``HttpAgentClient`` (remote, over the SSH tunnel) and ``LocalConnection``
(loopback/UDS) both implement it. Tests inject a fake here.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol, runtime_checkable

from armar_server.contracts import (
    AgentInfo,
    AppConfigUpdate,
    AppConfigView,
    InstanceCreate,
    InstanceDetail,
    InstanceSummary,
    JobRef,
    JobView,
    LifecycleEvent,
    StatusView,
)


@runtime_checkable
class AgentClient(Protocol):
    """One client == one connection to one `armar-agentd`."""

    async def info(self) -> AgentInfo: ...
    async def list_instances(self) -> list[InstanceSummary]: ...
    async def create_instance(self, payload: InstanceCreate) -> InstanceDetail: ...
    async def get_instance(self, slug: str) -> InstanceDetail: ...
    async def delete_instance(self, slug: str, *, force: bool = False) -> None: ...
    async def install(self, slug: str, *, no_validate: bool = False) -> JobRef: ...
    async def up(self, slug: str) -> JobRef: ...
    async def stop(self, slug: str) -> JobRef: ...
    async def restart(self, slug: str) -> JobRef: ...
    async def resolve(self, slug: str) -> JobRef: ...
    async def list_jobs(self) -> list[JobView]: ...
    async def cancel_job(self, job_id: str) -> None: ...
    async def job_events(
        self, job_id: str, last_event_id: int = 0
    ) -> AsyncIterator[LifecycleEvent]: ...
    async def get_status(self, slug: str) -> StatusView: ...
    async def get_config(self, slug: str) -> AppConfigView: ...
    async def put_config(self, slug: str, payload: AppConfigUpdate) -> AppConfigView: ...
    async def stream_logs(
        self, slug: str, tail: int = 50
    ) -> AsyncIterator[LifecycleEvent]: ...
    async def close(self) -> None: ...


__all__ = ["AgentClient"]
