"""Token storage and FastAPI dependency for the agent.

The token is generated by `armar-agentd install` and stored at
``<data_dir>/token`` (mode 0600). The dependency enforces it on every
request except ``/healthz``, ``/readyz``, and the SSE heartbeat path.
The token is **never** returned by ``GET /api/v1/info``.
"""

from __future__ import annotations

import contextlib
import secrets
from collections.abc import Coroutine
from dataclasses import dataclass
from pathlib import Path

from fastapi import Request

from .settings import AgentSettings

TOKEN_BYTES = 32  # 256-bit


@dataclass(frozen=True, slots=True)
class Token:
    value: str


class TokenStore:
    """File-backed token store with mode-0600 persistence."""

    def __init__(self, path: Path) -> None:
        self._path = path

    @property
    def path(self) -> Path:
        return self._path

    def exists(self) -> bool:
        return self._path.exists()

    def read(self) -> str:
        if not self._path.exists():
            raise FileNotFoundError(self._path)
        return self._path.read_text(encoding="utf-8").strip()

    def write(self, value: str) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._path.write_text(value, encoding="utf-8")
        with contextlib.suppress(OSError):  # not all platforms support chmod
            self._path.chmod(0o600)

    def rotate(self) -> str:
        new = secrets.token_urlsafe(TOKEN_BYTES)
        self.write(new)
        return new

    @staticmethod
    def generate() -> str:
        return secrets.token_urlsafe(TOKEN_BYTES)


def _build_token_dependency(
    settings: AgentSettings, store: TokenStore
) -> Coroutine[object, object, None]:
    """Build the FastAPI dependency that enforces the agent token.

    Routes do ``Depends(get_token_dep)`` (the closure built at app
    construction time, stashed on ``app.state.token_dep``).
    """
    from fastapi import HTTPException, status

    if settings.token_disabled:

        async def _noop() -> None:
            return None

        return _noop  # type: ignore[return-value]

    async def _dep(request: Request) -> None:
        auth = request.headers.get("Authorization") or request.headers.get("authorization")
        if not store.exists():
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="agent token not provisioned",
            )
        expected = store.read()
        if not auth:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="missing Authorization",
            )
        presented = auth.removeprefix("Bearer ").strip()
        if not secrets.compare_digest(presented, expected):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="invalid token",
            )
        return None

    return _dep  # type: ignore[return-value]


# Backwards-compat alias — old name kept for any external callers.
def make_token_dependency(
    settings: AgentSettings, store: TokenStore
) -> Coroutine[object, object, None]:
    return _build_token_dependency(settings, store)


async def get_token_dep(request: Request) -> None:  # type: ignore[no-untyped-def]
    """FastAPI dependency: delegate to the app-level token dependency.

    Routes do ``Depends(get_token_dep)`` (no parens). This function is a
    coroutine that FastAPI can introspect; it reads the *actual* token
    dependency from ``request.app.state.token_dep`` so it stays bound to
    the per-app ``AgentSettings`` / ``TokenStore``.
    """
    dep = request.app.state.token_dep
    await dep(request)


__all__ = [
    "Token",
    "TokenStore",
    "get_token_dep",
    "make_token_dependency",
]
